
# Test set: Load string keys with Annotated text VALUES
persons = {
    "raak/jan":"surname: raak. firstname: jan. dob:18nov1953",
    "horst/isabella":"surname: raak. firstname: isabella, clara, rosina, godena. maidenname:horst. dob:23nov1955",
    "raak/marloes":"surname: van hartingsvelt. firstname: marloes. maidenname:raak. dob:12sep1978",
    "raak/vincent":"surname: raak. firstname: vincent. dob:17nov1983",
    "raak/frans":"surname: raak. firstname: frans, reinder. dob:24oct1961",
    "raak/wilhelmina":"surname: van scheijen. firstname: wilhelmina, johanna. maidenname:raak. dob:15nov1965. nickname:jolanda. nickname:yolanda",
    "loevesijn/isabella":"surname: horst. firstname: isabella, clara, rosina, godena. maidenname:lovesijn. nickname:bep",
    }

expect = [ \
    #/* set 2*/
     {"v":"raak",  "f":"surname",  "k":["raak/jan","horst/isabella","raak/vincent", "raak/frans"]}, 
     {"v":"raak",  "f":"maidenname",  "k":["raak/marloes", "raak/wilhelmina"]}, 
     {"v":"18","f":"dob", "k":["raak/jan"]}, 
     {"v":"nov1953",  "f":"dob", "k":["raak/jan"]}, 
     {"v":"isabella",  "f":"firstname", "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"clara",  "f":"firstname",    "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"rosina",  "f":"firstname",  "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"godena",  "f":"firstname",  "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"23",  "f":"dob",  "k":["horst/isabella"]},
    {"v":"nov1955",  "f":"dob",  "k":["horst/isabella"]},
    {"v":"horst",  "f":"maidenname", "k":["horst/isabella"]},
    {"v":"van",  "f":"surname",  "k":["raak/marloes", "raak/wilhelmina"]},
    {"v":"hartingsvelt",  "f":"surname",   "k":["raak/marloes"]},
    {"v":"raak",  "f":"maidenname",   "k":["raak/marloes", "raak/wilhelmina"]},
    {"v":"vincent",  "f":"firstname",   "k":["raak/vincent"]},
    {"v":"12",  "f":"dob",   "k":["raak/marloes"]},
    {"v":"sep1978",  "f":"dob",  "k":["raak/marloes"]},
    {"v":"17",  "f":"dob",  "k":["raak/vincent"]},
    {"v":"nov1983",  "f":"dob",  "k":["raak/vincent"]},
    #/* set 2*/
     {"v":"raak",   "k":["raak/jan","horst/isabella","raak/marloes","raak/vincent", "raak/frans", "raak/wilhelmina"]}, 
     {"v":"18", "k":["raak/jan"]}, 
     {"v":"nov1953",   "k":["raak/jan"]}, 
     {"v":"isabella",   "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"clara",      "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"rosina",    "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"godena",    "k":["horst/isabella","loevesijn/isabella"]},
     {"v":"23",    "k":["horst/isabella"]},
    {"v":"nov1955",    "k":["horst/isabella"]},
    {"v":"horst",   "k":["horst/isabella","loevesijn/isabella"]},
    {"v":"van",    "k":["raak/marloes", "raak/wilhelmina"]},
    {"v":"hartingsvelt",     "k":["raak/marloes"]},
    {"v":"marloes",     "k":["raak/marloes"]},
    {"v":"vincent",     "k":["raak/vincent"]},
    {"v":"12",     "k":["raak/marloes"]},
    {"v":"sep1978",    "k":["raak/marloes"]},
    {"v":"17",    "k":["raak/vincent"]},
    {"v":"nov1983",    "k":["raak/vincent"]},
    {"q": ["18", "&", "nov1953"], "k":["raak/jan"]},
    {"q": ["18", "nov1953"], "k":["raak/jan"]},
    {"q": ["nov1955", "nov1953"], "k":["horst/isabella","raak/jan"]},
    {"q": ["raak", "&", "horst"], "k":["horst/isabella"]},
    {"q": ["raak", "|", "horst"], "k":['horst/isabella', 'loevesijn/isabella', 'raak/frans', 'raak/jan', 'raak/marloes', 'raak/vincent', 'raak/wilhelmina']},
    {"q": ["raak", "horst"], "k":['horst/isabella', 'loevesijn/isabella', 'raak/frans', 'raak/jan', 'raak/marloes', 'raak/vincent', 'raak/wilhelmina']},
]
