# Test set: Load string keys with Text 
book = {
    "genesis_1_1": "In the beginning God created the heavens and the earth.",
    "genesis_1_2": "Now the earth was formless and desolate, \
        and there was darkness upon the surface of the watery deep, \
        and God’s active force was moving about over the surface of the waters.",
    "genesis_1_3": "And God said: “Let there be light.” Then there was light.",
    "genesis_1_4": "After that God saw that the light was good, and God began to divide the light from the darkness.",
}
expect = [  # /* set 2*/
    {"v": "in", "k": ["genesis_1_1"]},
    {"v": "the", "k": ["genesis_1_1", "genesis_1_2", "genesis_1_4"]},
    {"v": "beginning", "k": ["genesis_1_1"]},
    {"v": "god", "k": ["genesis_1_1", "genesis_1_2", "genesis_1_3", "genesis_1_4"]},
    {"v": "created", "k": ["genesis_1_1"]},
    {"v": "heavens", "k": ["genesis_1_1"]},
    {"v": "and", "k": ["genesis_1_1", "genesis_1_2", "genesis_1_3", "genesis_1_4"]},
    {"v": "earth", "k": ["genesis_1_1", "genesis_1_2"]},
    {"v": "now", "k": ["genesis_1_2"]},
    {"v": "was", "k": ["genesis_1_2", "genesis_1_3", "genesis_1_4"]},
    {"v": "formless", "k": ["genesis_1_2"]},
    {"v": "desolate", "k": ["genesis_1_2"]},
    {"v": "there", "k": ["genesis_1_2", "genesis_1_3"]},
    {"v": "darkness", "k": ["genesis_1_2", "genesis_1_4"]},
    {"v": "upon", "k": ["genesis_1_2"]},
    {"v": "surface", "k": ["genesis_1_2"]},
    {"v": "of", "k": ["genesis_1_2"]},
    {"v": "watery", "k": ["genesis_1_2"]},
    {"v": "deep", "k": ["genesis_1_2"]},
    {"v": "s", "k": ["genesis_1_2"]},
    {"v": "active", "k": ["genesis_1_2"]},
    {"v": "force", "k": ["genesis_1_2"]},
    {"v": "moving", "k": ["genesis_1_2"]},
    {"v": "about", "k": ["genesis_1_2"]},
    {"v": "over", "k": ["genesis_1_2"]},
    {"v": "waters", "k": ["genesis_1_2"]},
    {"v": "said", "k": ["genesis_1_3"]},
    {"v": "Let", "k": ["genesis_1_3"]},
    {"v": "be", "k": ["genesis_1_3"]},
    {"v": "light", "k": ["genesis_1_3", "genesis_1_4"]},
    {"v": "After", "k": ["genesis_1_4"]},
    {"v": "that", "k": ["genesis_1_4"]},
    {"v": "saw", "k": ["genesis_1_4"]},
    {"v": "good", "k": ["genesis_1_4"]},
    {"v": "began", "k": ["genesis_1_4"]},
    {"v": "to", "k": ["genesis_1_4"]},
    {"v": "divide", "k": ["genesis_1_4"]},
    {"v": "from", "k": ["genesis_1_4"]},
    {"q": ["god", "&", "created"], "k": ["genesis_1_1"]},
    {"q": ["god", "|", "created"], "k": ["genesis_1_1", "genesis_1_2"]},
    {"q": ["god", "created"], "k": ["genesis_1_1", "genesis_1_2"]},
    {
        "q": ["active", "force", "created", "light"],
        "k": ["genesis_1_1", "genesis_1_2", "genesis_1_3", "genesis_1_4"],
    },
    {
        "q": ["( active & force) | ( created & god )"],
        "k": ["genesis_1_1", "genesis_1_2"],
    },
    {
        "q": ["(", "active", "&", "force", ")", "|", "(", "created", "&", "god", ")"],
        "k": ["genesis_1_1", "genesis_1_2"],
    },
]
