# Test set: Load string keys with Text
cars = {
    "tesla/s": "Make: Tesla. Model S. Range: 375; price: 104490.",
    "tesla/y/p": "Make: Tesla. Model Y, performance. Range: 303; price: 67990.",
    "tesla/y/lr": "Make: Tesla. Model Y, long range. Range: 318; price: 64990.",
    "tesla/x": "Make: Tesla. Model X. Range: 332; price: 120490.",
    "tesla/3": "Make: Tesla. Model 3. Range: 267; price: 48490.",
    "tesla/3/p": "Make: Tesla. Model 3, performance. Range: 315; price: 62490.",
    "tesla/3/lr": "Make: Tesla. Model 3, long range. Range: 334; price: 57490.",
    "volvo/C40": "Make: Volvo. Model C40. Range: 226; price: 59845.",
    "volvo/XC40": "Make: Volvo. Model XC40. Range: 223; price: 56395.",
    "ford/mustang-e/cr1": "Make: Ford. Model: Mustang Mach-E California Route 1. Range: 305; price: 52450.",
    "ford/mustang-e/p": "Make: Ford. Model: Mustang Mach-E	Premium. Range:303; price: 48775.",
    "ford/mustang-e/er": "Make: Ford. Model: Mustang Mach-E ER. Range:284; price: 68502.",
    "ford/mustang-e/e": "Make: Ford. Model: Mustang Mach-E	Select. Range:247; price: 43895.",
    "jaguar/ipace/": "Make: Jaguar. Model: I-PACE. Range:258; price: 71050.",
    "fisker/ocean/extreme": "Make: Fisker. Model: Ocean	Extreme. Range:350; price: 68999.",
    "fisker/ocean/one": "Make: Fisker. Model: Ocean	One. Range:350; price: 68999.",
    "fisker/ocean/ultra": "Make: Fisker. Model: Ocean	Ultra. Range:340; price: 49999.",
    "fisker/ocean/sport": "Make: Fisker. Model: Ocean	Sport. Range:250; price: 37499.",
}
expect = [  # /* set 2*/
    {
        "pp": "yes",
        "q": ["range", ">=", "300"],
        "k": [
            "fisker/ocean/extreme",
            "fisker/ocean/sport",
            "fisker/ocean/ultra",
            "ford/mustang-e/cr1",
            "ford/mustang-e/p",
            "tesla/3/p",
            "tesla/3/lr",
            "tesla/s",
            "tesla/x",
            "tesla/y/lr",
            "tesla/y/p",
        ],
    },
    {
        "pp": "yes",
        "q": ["price", "<=", "60000"],
        "k": [
            "fisker/ocean/sport",
            "fisker/ocean/ultra",
            "ford/mustang-e/e",
            "ford/mustang-e/cr1",
            "ford/mustang-e/p",
            "tesla/3",
            "tesla/3/lr",
            "tesla/3/p",
            "volvo/C40",
            "volvo/XC40",
        ],
    },
    {
        "pp": "yes",
        "q": ["(", "range", ">=", "300", ")", "&&", "(", "price", "<=", "60000", ")"],
        "k": [
            "fisker/ocean/ultra",
            "ford/mustang-e/p",
            "tesla/3/lr",
        ],
    },
    {
        "pp": "yes",
        "q": ["range", ">=", "300", "&", "price", "<=", "60000"],
        "k": [
            "fisker/ocean/ultra",
            "ford/mustang-e/p",
            "tesla/3/lr",
        ],
    },
]
