import redis
from match import Matcher

def SD_101_Non_Intrusive_Indexing_And_Full_Text_Queries(cluster_id, controller, data, index):
    matcher = Matcher("SD_101_Non_Intrusive_Indexing_And_Full_Text_Queries")

    scenario = [
        {"step": "get test data", "node": data, "command": "g.wget https://roxoft.dev/assets/dataset1.txt", "expects": b'dataset1.txt'},
        {"step": "load test data", "node": data, "command": "load.text CRLF TAB_SEPARATED FROM dataset1.txt as_hash", "expects": b'OK'},
        {"step": "check RMA", "node": data, "command": "HGETALL RMA", "expects": {b'city': b'Amsterdam', b'image': b"%3cimg src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F5e%2Fcc%2Ff2%2F5eccf24b7022983b2720c775024a9ecf.jpg&f=1&nofb=1&ipt=507f7a6205ea437709b67b294c570649002891ece616d1b59fc6200d799268b5&ipo=images' style='max-width: 60px%26'/%3e", b'country': b'Netherlands', b'identity': b'Rijksmuseum', b'Year_Founded': b'1798', b'state': b'NH', b'categories': b'museum,art,rembrandt,vermeer,asselijn,cuyp,breitner,coorte,venne,borch,jans,versprong,ruisdael,fabritius,avercamp,gilliszleyster,claesz,hals,paintings'}},
        {"step": "wait indexing completed", "node": data, "command": "rxIndex wait", "expects": b'OK'},

        {"step": "verify QUERY science or nature", "node":data, "command": "Q science nature ranked", "expects": [[b'key', b'RMB', b'score', b'2.000000', b'value', [b'city', b'Leiden', b'image', b"%3cimg src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.Lv9_mPRli6a1L7dagFzrvAHaFj%26pid%3DApi&f=1&ipt=081ccd221acb484b7f3a6f6ad6bfa4be0759b8b2a23a31160a664352833708c6&ipo=images' style='max-width: 60px%26'/%3e", b'country', b'Netherlands', b'identity', b'Boerhave Museum', b'Year_Founded', b'1931', b'state', b'ZH', b'categories', b'museum,science,art,nature']], [b'key', b'SI', b'score', b'2.000000', b'value', [b'city', b'Washington', b'image', b"%3cimg src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.IQ3jR9DHnZd5l26wtAIhHgHaE7%26pid%3DApi&f=1&ipt=c976c1afdbef655da0b3276aee033fe1a113709fac6d78cc7be321a21d10eb24&ipo=images' style='max-width: 60px%26'/%3e", b'country', b'USA', b'identity', b'Smithsonian', b'Year_Founded', b'1846', b'state', b'DC', b'categories', b'museum,science,nature']], [b'key', b'BBJ', b'score', b'1.000000', b'value', [b'identity', b'Bouley Bay', b'city', b'Jersey', b'categories', b'landmark,recreation,nature', b'country', b'United Kingdom', b'image', b"%3cimg src='https://www.responsibletravel.com/ImagesClient/dtg-cr5732-jersey-bouley-bay.jpg' style='max-width: 60px%26'/%3e"]], [b'key', b'BNJ', b'score', b'1.000000', b'value', [b'country', b'USA', b'city', b'New Jersey', b'image', b"%3cimg src='https://www.planetware.com/wpimages/2022/03/new-jersey-top-attractions-new-jersey-beaches-wildwood-crest-beach.jpg' style='max-width: 60px%26'/%3e", b'identity', b'New Jersey Beaches', b'state', b'NJ', b'categories', b'landmark,beach,nature,recreation']], [b'key', b'CPJ', b'score', b'1.000000', b'value', [b'identity', b'Corbiere Point', b'city', b'Jersey', b'categories', b'landmark,recreation,nature', b'country', b'United Kingdom', b'image', b"%3cimg src='https://www.responsibletravel.com/ImagesClient/dtg-cr5732-jersey-corbiere-point.jpg' style='max-width: 60px%26'/%3e"]], [b'key', b'DWGNJ', b'score', b'1.000000', b'value', [b'country', b'USA', b'city', b'New Jersey', b'image', b"%3cimg src='https://www.planetware.com/photos-large/USNJ/us-new-jersey-delaware-water-gap-national-recreation-area.jpg' style='max-width: 60px%26'/%3e", b'identity', b'Delaware Water Gap National Recreation Area', b'state', b'NJ', b'categories', b'landmark,nature,recreation']], [b'key', b'PNJ', b'score', b'0.500000', b'value', [b'country', b'USA', b'city', b'New Jersey', b'image', b"%3cimg src='https://www.planetware.com/wpimages/2022/03/new-jersey-top-attractions-princeton-battlefield-state-park-institute.jpg' style='max-width: 60px%26'/%3e", b'identity', b'Princeton Battlefield State Park & Institute for Advanced Study', b'state', b'NJ', b'categories', b'science,science,research,einstein,park']]]},
        {"step": "verify QUERY science and nature", "node":data, "command": "RXQUERY science & nature ranked", "expects": [[b'key', b'RMB', b'type', b'H', b'score', b'2.000000'], [b'key', b'SI', b'type', b'H', b'score', b'2.000000']]},
        {"step": "verify QUERY older museums", "node":data, "command": "RXQUERY year_founded < 1900 ranked", "expects": [[b'key', b'BM', b'type', b'H', b'score', b'1.000000'], [b'key', b'CTY', b'type', b'H', b'score', b'1.000000'], [b'key', b'FCNO', b'type', b'H', b'score', b'1.000000'], [b'key', b'HSPR', b'type', b'H', b'score', b'1.000000'], [b'key', b'MBAO', b'type', b'H', b'score', b'1.000000'], [b'key', b'LP', b'type', b'H', b'score', b'1.000000'], [b'key', b'MH', b'type', b'H', b'score', b'1.000000'], [b'key', b'RMA', b'type', b'H', b'score', b'1.000000'], [b'key', b'RSNO', b'type', b'H', b'score', b'1.000000'], [b'key', b'SI', b'type', b'H', b'score', b'1.000000'], [b'key', b'SY', b'type', b'H', b'score', b'1.000000'], [b'key', b'TG', b'type', b'H', b'score', b'1.000000'], [b'key', b'APAZNO', b'type', b'H', b'score', b'1.000000'], [b'key', b'SBNNO', b'type', b'H', b'score', b'1.000000'], [b'key', b'VCMNJ', b'type', b'H', b'score', b'1.000000']]},
    ]
    matcher.play(scenario)
